# data_clean 2


编码 + 填空 +

In [1]:
import pandas as pd


df = pd.read_csv("./toUser_train_data-Copy1.csv",index_col=False)
df.pop('用户标识')
df.head()

,年龄,用户状态,性别,网龄,客户类型,城县农标志,是否4G客户,用户星级,同身份证下的号码数,是否全球通客户,...,上月游戏类流量占比,上月音乐类流量占比,上月视频类流量占比,上月短视频类流量占比,是否订购5G套餐,用户常驻地是否在5G基站3公里范围,是否资费敏感客户,新5G终端品牌,新5G终端档次,标签月
0,25,1,0,16,1,2,1,1,1,1,...,0.000,0.0,0.000,0.0017,0,1,0,一加,2,6
1,24,1,1,57,1,2,1,1,1,0,...,0.000,0.0,0.000,0.0000,0,1,0,华为,4,6
2,63,1,0,147,1,2,1,3,1,1,...,0.001,0.0,0.013,0.3631,0,1,0,OPPO,2,6
3,29,1,0,70,1,2,1,3,1,1,...,0.000,0.0,0.000,0.0155,1,1,0,华为,4,6
4,30,3,0,11,1,0,1,1,1,1,...,0.000,0.0,0.000,0.0000,0,0,0,OPPO,3,6

In [2]:
# 查看每一列的数值类型
column_types = df.dtypes

# 找到非数值类型的列
non_numeric_columns = column_types[column_types != 'float64'][column_types != 'int64']

# 打印非数值类型的列及其缺失值个数
for column in df.columns:
    missing_values = df[column].isnull().sum()
    if missing_values != 0 or column_types[column] == 'object':
        print(f"列名：{column}，数据类型： {column_types[column]}，\n 缺失值个数：{missing_values}")
        print('\n')

列名：上月主套餐费用，数据类型： float64，
 缺失值个数：14304


列名：上月主套内包含流量，数据类型： float64，
 缺失值个数：14304


列名：上月ARPU，数据类型： float64，
 缺失值个数：22954


列名：上上月ARPU，数据类型： float64，
 缺失值个数：32921


列名：上上上月ARPU，数据类型： float64，
 缺失值个数：39126


列名：历史终端使用平均时长，数据类型： float64，
 缺失值个数：81478


列名：近三年换终端次数，数据类型： float64，
 缺失值个数：279160


列名：当前终端品牌，数据类型： object，
 缺失值个数：147700


列名：当前终端价格，数据类型： float64，
 缺失值个数：157310


列名：当前终端价格档次，数据类型： float64，
 缺失值个数：147700


列名：当前终端是否双卡槽，数据类型： float64，
 缺失值个数：157299


列名：当前终端使用时长，数据类型： float64，
 缺失值个数：147700


列名：上次终端品牌，数据类型： object，
 缺失值个数：147700


列名：上次终端价格，数据类型： float64，
 缺失值个数：187911


列名：上次终端价格档次，数据类型： float64，
 缺失值个数：147700


列名：上次终端是否双卡槽，数据类型： float64，
 缺失值个数：187810


列名：上次终端使用时长，数据类型： float64，
 缺失值个数：81478


列名：上上次终端品牌，数据类型： object，
 缺失值个数：147700


列名：上上次终端价格，数据类型： float64，
 缺失值个数：211905


列名：上上次终端价格档次，数据类型： float64，
 缺失值个数：147700


列名：上上次终端是否双卡槽，数据类型： float64，
 缺失值个数：211592


列名：上上次终端使用时长，数据类型： float64，
 缺失值个数：130933


列名：上月DOU，数据类型： float64，
 缺失值个数：59276


列名：上上月DOU，数据类型： float64，
 缺失值个数：68565


列名：上上上月DOU，数据类型： float64，
 缺失值个数：73834


列名：上上月流量饱和度，数据类型： float64，
 缺失值个数：12781


列名：上上上月流量饱和度，数据类型： float64，
 缺失值个数：26245


列名：上月限速次数，数据类型： float64，
 缺失值个数：526153


列名：上月2，数据类型： float64，
 缺失值个数：59276


列名：近三月限速次数，数据类型： float64，
 缺失值个数：510265


列名：近三月2，数据类型： float64，
 缺失值个数：59276


列名：近3月月均上网天数，数据类型： float64，
 缺失值个数：90454


列名：家庭交往圈终端品牌偏好，数据类型： object，
 缺失值个数：147700


列名：用户历史终端品牌偏好，数据类型： object，
 缺失值个数：0


列名：集团交往圈终端品牌偏好，数据类型： object，
 缺失值个数：0


列名：新5G终端品牌，数据类型： object，
 缺失值个数：0

# 编码

In [3]:
# 定义需要编码的列
columns_to_check = [
    '当前终端品牌',
    '上次终端品牌',
    '上上次终端品牌',
    '家庭交往圈终端品牌偏好',
    '用户历史终端品牌偏好',
    '集团交往圈终端品牌偏好',
    '新5G终端品牌'
]

# 定义类别和对应整数的字典
category_mapping = {
    '华为': 1,
    '苹果': 2,
    'vivo': 3,
    'OPPO': 4,
    '荣耀': 5,
    '小米': 6,
    '三星': 7,
    '魅族': 8,
    '金立': 9,
    '中兴': 10,
    '一加': 11,
    '中国移动': 12,
        '其他': 13
}

# 循环处理每一列并进行编码
for column in columns_to_check:
    if column in df.columns:
        df[column] = df[column].replace(category_mapping)
df.head()

,年龄,用户状态,性别,网龄,客户类型,城县农标志,是否4G客户,用户星级,同身份证下的号码数,是否全球通客户,...,上月游戏类流量占比,上月音乐类流量占比,上月视频类流量占比,上月短视频类流量占比,是否订购5G套餐,用户常驻地是否在5G基站3公里范围,是否资费敏感客户,新5G终端品牌,新5G终端档次,标签月
0,25,1,0,16,1,2,1,1,1,1,...,0.000,0.0,0.000,0.0017,0,1,0,11,2,6
1,24,1,1,57,1,2,1,1,1,0,...,0.000,0.0,0.000,0.0000,0,1,0,1,4,6
2,63,1,0,147,1,2,1,3,1,1,...,0.001,0.0,0.013,0.3631,0,1,0,4,2,6
3,29,1,0,70,1,2,1,3,1,1,...,0.000,0.0,0.000,0.0155,1,1,0,1,4,6
4,30,3,0,11,1,0,1,1,1,1,...,0.000,0.0,0.000,0.0000,0,0,0,4,3,6

In [4]:
# 查看每一列的数值类型
column_types = df.dtypes

# 找到非数值类型的列
non_numeric_columns = column_types[column_types != 'float64'][column_types != 'int64']

# 打印非数值类型的列及其缺失值个数
for column in df.columns:
    missing_values = df[column].isnull().sum()
    if missing_values != 0 or column_types[column] == 'object':
        print(f"列名：{column}，数据类型： {column_types[column]}，\n 缺失值个数：{missing_values}")
        print('\n')

列名：上月主套餐费用，数据类型： float64，
 缺失值个数：14304


列名：上月主套内包含流量，数据类型： float64，
 缺失值个数：14304


列名：上月ARPU，数据类型： float64，
 缺失值个数：22954


列名：上上月ARPU，数据类型： float64，
 缺失值个数：32921


列名：上上上月ARPU，数据类型： float64，
 缺失值个数：39126


列名：历史终端使用平均时长，数据类型： float64，
 缺失值个数：81478


列名：近三年换终端次数，数据类型： float64，
 缺失值个数：279160


列名：当前终端品牌，数据类型： float64，
 缺失值个数：147700


列名：当前终端价格，数据类型： float64，
 缺失值个数：157310


列名：当前终端价格档次，数据类型： float64，
 缺失值个数：147700


列名：当前终端是否双卡槽，数据类型： float64，
 缺失值个数：157299


列名：当前终端使用时长，数据类型： float64，
 缺失值个数：147700


列名：上次终端品牌，数据类型： float64，
 缺失值个数：147700


列名：上次终端价格，数据类型： float64，
 缺失值个数：187911


列名：上次终端价格档次，数据类型： float64，
 缺失值个数：147700


列名：上次终端是否双卡槽，数据类型： float64，
 缺失值个数：187810


列名：上次终端使用时长，数据类型： float64，
 缺失值个数：81478


列名：上上次终端品牌，数据类型： float64，
 缺失值个数：147700


列名：上上次终端价格，数据类型： float64，
 缺失值个数：211905


列名：上上次终端价格档次，数据类型： float64，
 缺失值个数：147700


列名：上上次终端是否双卡槽，数据类型： float64，
 缺失值个数：211592


列名：上上次终端使用时长，数据类型： float64，
 缺失值个数：130933


列名：上月DOU，数据类型： float64，
 缺失值个数：59276


列名：上上月DOU，数据类型： float64，
 缺失值个数：68565


列名：上上上月DOU，数据类型： float64，
 缺失值个数：73834


列名：上上月流量饱和度，数据类型： float64，
 缺失值个数：12781


列名：上上上月流量饱和度，数据类型： float64，
 缺失值个数：26245


列名：上月限速次数，数据类型： float64，
 缺失值个数：526153


列名：上月2，数据类型： float64，
 缺失值个数：59276


列名：近三月限速次数，数据类型： float64，
 缺失值个数：510265


列名：近三月2，数据类型： float64，
 缺失值个数：59276


列名：近3月月均上网天数，数据类型： float64，
 缺失值个数：90454


列名：家庭交往圈终端品牌偏好，数据类型： float64，
 缺失值个数：147700

# 众数 填缺失值

In [5]:
columns_with_missing_values = df.columns[df.isnull().any()].tolist()
columns_with_missing_values

['上月主套餐费用',
 '上月主套内包含流量',
 '上月ARPU',
 '上上月ARPU',
 '上上上月ARPU',
 '历史终端使用平均时长',
 '近三年换终端次数',
 '当前终端品牌',
 '当前终端价格',
 '当前终端价格档次',
 '当前终端是否双卡槽',
 '当前终端使用时长',
 '上次终端品牌',
 '上次终端价格',
 '上次终端价格档次',
 '上次终端是否双卡槽',
 '上次终端使用时长',
 '上上次终端品牌',
 '上上次终端价格',
 '上上次终端价格档次',
 '上上次终端是否双卡槽',
 '上上次终端使用时长',
 '上月DOU',
 '上上月DOU',
 '上上上月DOU',
 '上上月流量饱和度',
 '上上上月流量饱和度',
 '上月限速次数',
 '上月2',
 '近三月限速次数',
 '近三月2',
 '近3月月均上网天数',
 '家庭交往圈终端品牌偏好']

In [6]:
import pandas as pd

def fill_missing_with_mode(df):
    """
    遍历 DataFrame 的所有列，并使用众数填充缺失值
    Args:
        df: pandas DataFrame，需要处理的数据集

    Returns:
        filled_df: pandas DataFrame，填充缺失值后的数据集
    """
    filled_df = df.copy()

    # 遍历每列
    for col in filled_df.columns:
        # 获取当前列的众数
        mode_val = filled_df[col].mode()[0]

        # 使用众数填充缺失值
        filled_df[col].fillna(mode_val, inplace=True)

    return filled_df

# 调用函数填充缺失值
filled_df = fill_missing_with_mode(df)

In [7]:
columns_with_missing_values = filled_df.columns[filled_df.isnull().any()].tolist()
columns_with_missing_values

[]

In [9]:
filled_df.to_csv("./data_new.csv",index=False)

In [8]:
filled_df.head()

,年龄,用户状态,性别,网龄,客户类型,城县农标志,是否4G客户,用户星级,同身份证下的号码数,是否全球通客户,...,上月游戏类流量占比,上月音乐类流量占比,上月视频类流量占比,上月短视频类流量占比,是否订购5G套餐,用户常驻地是否在5G基站3公里范围,是否资费敏感客户,新5G终端品牌,新5G终端档次,标签月
0,25,1,0,16,1,2,1,1,1,1,...,0.000,0.0,0.000,0.0017,0,1,0,11,2,6
1,24,1,1,57,1,2,1,1,1,0,...,0.000,0.0,0.000,0.0000,0,1,0,1,4,6
2,63,1,0,147,1,2,1,3,1,1,...,0.001,0.0,0.013,0.3631,0,1,0,4,2,6
3,29,1,0,70,1,2,1,3,1,1,...,0.000,0.0,0.000,0.0155,1,1,0,1,4,6
4,30,3,0,11,1,0,1,1,1,1,...,0.000,0.0,0.000,0.0000,0,0,0,4,3,6

In [10]:
filled_df

,年龄,用户状态,性别,网龄,客户类型,城县农标志,是否4G客户,用户星级,同身份证下的号码数,是否全球通客户,...,上月游戏类流量占比,上月音乐类流量占比,上月视频类流量占比,上月短视频类流量占比,是否订购5G套餐,用户常驻地是否在5G基站3公里范围,是否资费敏感客户,新5G终端品牌,新5G终端档次,标签月
0,25,1,0,16,1,2,1,1,1,1,...,0.0000,0.0000,0.0000,0.0017,0,1,0,11,2,6
1,24,1,1,57,1,2,1,1,1,0,...,0.0000,0.0000,0.0000,0.0000,0,1,0,1,4,6
2,63,1,0,147,1,2,1,3,1,1,...,0.0010,0.0000,0.0130,0.3631,0,1,0,4,2,6
3,29,1,0,70,1,2,1,3,1,1,...,0.0000,0.0000,0.0000,0.0155,1,1,0,1,4,6
4,30,3,0,11,1,0,1,1,1,1,...,0.0000,0.0000,0.0000,0.0000,0,0,0,4,3,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557653,-1,1,-1,56,1,2,1,2,1,1,...,0.0003,0.0402,0.0979,0.1078,0,0,0,1,3,6
557654,23,1,0,57,1,0,1,1,1,0,...,0.0093,0.0085,0.0245,0.0130,0,0,0,7,5,6
557655,-1,1,-1,24,1,2,1,1,2,1,...,0.0005,0.0001,0.4035,0.2125,0,0,0,1,3,6
557656,-1,1,-1,236,1,2,1,3,1,1,...,0.0000,0.0000,0.0000,0.0000,0,1,0,1,5,6
557657,27,1,0,137,1,2,1,3,1,1,...,0.0000,0.0007,0.0001,0.6321,1,0,0,1,5,6